import React from 'react';
import './InfoModal.css';

function InfoModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2>How to Play</h2>
          <button className="close-button" onClick={onClose}>×</button>
        </div>

        <div className="info-content">
          <section className="how-to-play">
            <h3>🎯 The Goal</h3>
            <p>
              Solve the daily puzzle generated by AI models before the 24-hour window ends.
              AI models compete to create challenging puzzles that stump human players!
            </p>
          </section>

          <section className="puzzle-types">
            <h3>🧩 Puzzle Categories</h3>
            <div className="category-list">
              <div className="category-item">
                <span className="category-icon">🔢</span>
                <div className="category-details">
                  <strong>Math Puzzles</strong>
                  <p>Algebra equations, physics problems, number theory, geometry</p>
                </div>
              </div>
              <div className="category-item">
                <span className="category-icon">📝</span>
                <div className="category-details">
                  <strong>Word Puzzles</strong>
                  <p>Riddles, anagrams, word searches, clever wordplay</p>
                </div>
              </div>
              <div className="category-item">
                <span className="category-icon">🎨</span>
                <div className="category-details">
                  <strong>Art Puzzles</strong>
                  <p>Music identification, visual recognition, art history</p>
                </div>
              </div>
            </div>
          </section>

          <section className="difficulty-system">
            <h3>⚖️ Dynamic Difficulty</h3>
            <div className="difficulty-tiers">
              <div className="tier-item mini">
                <span className="tier-badge">Mini</span>
                <span className="tier-range">0.0 - 0.39</span>
                <span className="tier-description">Beginner friendly</span>
              </div>
              <div className="tier-item mid">
                <span className="tier-badge">Mid</span>
                <span className="tier-range">0.4 - 0.69</span>
                <span className="tier-description">Standard challenge</span>
              </div>
              <div className="tier-item beast">
                <span className="tier-badge">Beast</span>
                <span className="tier-range">0.7 - 1.0</span>
                <span className="tier-description">Expert level</span>
              </div>
            </div>
            <p className="difficulty-explanation">
              Difficulty adjusts daily based on community performance:
            </p>
            <ul className="difficulty-rules">
              <li>✅ Community solves → Harder tomorrow (+0.05)</li>
              <li>❌ AI stumps everyone → Easier tomorrow (-0.05)</li>
            </ul>
          </section>

          <section className="ai-rotation">
            <h3>🤖 AI Model Rotation</h3>
            <p>
              Different AI models take turns generating puzzles. Each model has its own 
              style and strengths. Check the Stump Tally to see which models are most 
              successful at challenging human players!
            </p>
            <div className="model-list">
              <span className="model-tag">Claude-4</span>
              <span className="model-tag">GPT-5</span>
              <span className="model-tag">Gemini</span>
            </div>
          </section>

          <section className="tips">
            <h3>💡 Tips</h3>
            <ul className="tips-list">
              <li>Take your time - you have 24 hours!</li>
              <li>Read the question carefully</li>
              <li>For math problems, show your work step by step</li>
              <li>For word puzzles, think creatively</li>
              <li>Check your answer before submitting</li>
              <li>Come back daily for new challenges</li>
            </ul>
          </section>

          <section className="sharing">
            <h3>📱 Sharing</h3>
            <p>
              Share your results without spoilers! The share feature creates a 
              summary that shows whether you solved it without revealing the answer.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}

export default InfoModal;