import React, { useState } from 'react';
import './Puzzle.css';

function Puzzle() {
  const [answer, setAnswer] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const [isCorrect, setIsCorrect] = useState(false);

  // Mock puzzle data - will be replaced with API call
  const puzzle = {
    id: '2025-08-03',
    category: 'math',
    difficulty: 0.58,
    generator_model: 'claude-3',
    question: 'Solve for x: 3x² + 7x - 20 = 0',
    solution: 'x = 5/3 or x = -4'
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setSubmitted(true);
    // Mock validation - will be replaced with API call
    setIsCorrect(answer.toLowerCase().includes('5/3') && answer.toLowerCase().includes('-4'));
  };

  const getDifficultyColor = (difficulty) => {
    if (difficulty < 0.4) return '#28a745'; // Green for Mini
    if (difficulty < 0.7) return '#ffc107'; // Yellow for Mid
    return '#dc3545'; // Red for Beast
  };

  const getDifficultyLabel = (difficulty) => {
    if (difficulty < 0.4) return 'Mini';
    if (difficulty < 0.7) return 'Mid';
    return 'Beast';
  };

  return (
    <div className="puzzle-page">
      <div className="puzzle-container">
        <div className="puzzle-header">
          <h1>Today's Puzzle</h1>
          <div className="puzzle-meta">
            <div className="meta-item">
              <span className="meta-label">Category:</span>
              <span className="meta-value">{puzzle.category}</span>
            </div>
            <div className="meta-item">
              <span className="meta-label">Difficulty:</span>
              <span 
                className="meta-value difficulty-badge"
                style={{ backgroundColor: getDifficultyColor(puzzle.difficulty) }}
              >
                {getDifficultyLabel(puzzle.difficulty)} ({puzzle.difficulty})
              </span>
            </div>
            <div className="meta-item">
              <span className="meta-label">Generated by:</span>
              <span className="meta-value">{puzzle.generator_model}</span>
            </div>
          </div>
        </div>

        <div className="puzzle-content">
          <div className="question-card">
            <h2>Question</h2>
            <p className="question">{puzzle.question}</p>
          </div>

          {!submitted ? (
            <form onSubmit={handleSubmit} className="answer-form">
              <div className="form-group">
                <label htmlFor="answer">Your Answer:</label>
                <input
                  type="text"
                  id="answer"
                  value={answer}
                  onChange={(e) => setAnswer(e.target.value)}
                  placeholder="Enter your answer here..."
                  required
                />
              </div>
              <button type="submit" className="submit-button">
                Submit Answer
              </button>
            </form>
          ) : (
            <div className={`result-card ${isCorrect ? 'correct' : 'incorrect'}`}>
              <div className="result-icon">
                {isCorrect ? '✅' : '❌'}
              </div>
              <h3>{isCorrect ? 'Correct!' : 'Incorrect'}</h3>
              <p className="your-answer">Your answer: {answer}</p>
              <p className="correct-answer">Correct answer: {puzzle.solution}</p>
              {isCorrect && (
                <div className="success-message">
                  <p>🎉 Great job! You solved today's puzzle!</p>
                  <p>Come back tomorrow for a new challenge.</p>
                </div>
              )}
            </div>
          )}
        </div>

        <div className="puzzle-info">
          <div className="info-card">
            <h3>How it works</h3>
            <ul>
              <li>Each day, an AI model generates a new puzzle</li>
              <li>You have 24 hours to solve it</li>
              <li>Difficulty adjusts based on community performance</li>
              <li>If everyone solves it, tomorrow gets harder (+0.05)</li>
              <li>If AI stumps everyone, tomorrow gets easier (-0.05)</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Puzzle;