# Generated by Django 4.2.7 on 2025-08-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='generator_model',
            field=models.CharField(choices=[('gpt5', 'GPT-5'), ('claude4', 'Claude-4'), ('gemini', 'Gemini')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stumptally',
            name='ai_model',
            field=models.CharField(choices=[('gpt5', 'GPT-5'), ('claude4', 'Claude-4'), ('gemini', 'Gemini')], max_length=20),
        ),
    ]
